# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-24 20:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accountsIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('payment_fees', models.FloatField(default=0)),
                ('service_fees', models.FloatField(default=0)),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=10, null=True)),
                ('total_fees', models.FloatField()),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('amount_to_pay', models.FloatField(blank=True, default=0, null=True)),
                ('staff', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='accountsOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('charge', models.FloatField(default=0)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('staff', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='bankAccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50, unique=True)),
                ('opening_balance', models.FloatField(default=0, max_length=10)),
                ('opening_balance_date', models.DateField(default=datetime.date.today)),
                ('current_balance', models.FloatField(default=0, max_length=10)),
                ('margin_amount', models.FloatField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bankBalanceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('opening_balance', models.FloatField(default=0, max_length=10)),
                ('closing_balance', models.FloatField(default=0, max_length=10)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bankAccountDetails')),
            ],
        ),
        migrations.CreateModel(
            name='bankRechargeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bankAccountDetails')),
            ],
        ),
        migrations.CreateModel(
            name='recieptDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ass_fees', models.FloatField(blank=True, default=0, max_length=10)),
                ('reciept_title', models.CharField(max_length=50)),
                ('service_fees', models.FloatField(blank=True, default=0, max_length=10)),
                ('ass_bank_acc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bankAccountDetails')),
            ],
        ),
        migrations.CreateModel(
            name='recieptDetailsOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept_title', models.CharField(blank=True, max_length=50)),
                ('charge', models.FloatField(default=0)),
                ('ass_bank_acc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bankAccountDetails')),
            ],
        ),
        migrations.AddField(
            model_name='accountsout',
            name='bank_acc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bankAccountDetails'),
        ),
        migrations.AddField(
            model_name='accountsout',
            name='reciept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.recieptDetailsOut'),
        ),
        migrations.AddField(
            model_name='accountsin',
            name='bank_acc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bankAccountDetails'),
        ),
        migrations.AddField(
            model_name='accountsin',
            name='reciept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.recieptDetail'),
        ),
        migrations.AlterUniqueTogether(
            name='bankbalancedetails',
            unique_together=set([('bank', 'date')]),
        ),
    ]
