# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 04:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountsIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('reciept', models.CharField(choices=[(b'aadhar', b'Aadhar'), (b'egrats', b'E Grants')], max_length=100)),
                ('bank_acc', models.CharField(blank=True, max_length=50)),
                ('payment_fees', models.FloatField()),
                ('service_fees', models.FloatField()),
                ('customer_name', models.CharField(max_length=50)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('contact_no', models.CharField(max_length=10, null=True)),
                ('total_fees', models.FloatField()),
                ('remark', models.CharField(max_length=200)),
                ('staff', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='accounts',
        ),
    ]
