# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-24 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbalancedetails',
            name='closing_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bankbalancedetails',
            name='opening_balance',
            field=models.FloatField(default=0),
        ),
    ]
