# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170908_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='recieptDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='accountsin',
            name='reciept',
            field=models.CharField(max_length=100),
        ),
    ]
