# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170908_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieptdetails',
            name='ass_bank_acc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recieptdetails',
            name='service_fees',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
