# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170908_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankAccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_branch', models.CharField(max_length=50)),
                ('bank_acc_no', models.CharField(max_length=15)),
                ('acc_holder', models.CharField(max_length=50)),
                ('acc_holder_contactno', models.CharField(max_length=10)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='accountsin',
            name='remark',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recieptdetails',
            name='ass_bank_acc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recieptdetails',
            name='service_fees',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
