# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 01:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170910_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountsOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('reciept', models.CharField(max_length=100)),
                ('bank_acc', models.CharField(blank=True, max_length=50)),
                ('charge', models.FloatField()),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('staff', models.CharField(max_length=50)),
            ],
        ),
    ]
