# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_bankaccountdetails_bank_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccountdetails',
            name='balance',
        ),
    ]
