# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_bankaccountdetails_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccountdetails',
            name='acc_holder',
        ),
        migrations.RemoveField(
            model_name='bankaccountdetails',
            name='acc_holder_contactno',
        ),
        migrations.RemoveField(
            model_name='bankaccountdetails',
            name='bank_acc_no',
        ),
    ]
