# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_bankaccountdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankAccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('opening_balance', models.FloatField()),
                ('opening_balance_date', models.DateField()),
            ],
        ),
    ]
