# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_bankaccountdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountdetails',
            name='opening_balance',
            field=models.FloatField(max_length=10),
        ),
    ]
