# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20171106_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieptdetails',
            name='service_fees',
            field=models.FloatField(blank=True, default=0, max_length=10),
        ),
    ]
