# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20171107_0235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recieptDetails',
        ),
    ]
