# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delete_recieptdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='recieptDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ass_fees', models.CharField(default='0', max_length=10)),
                ('reciept_title', models.CharField(max_length=50)),
                ('ass_bank_acc', models.CharField(blank=True, max_length=50, null=True)),
                ('service_fees', models.FloatField(blank=True, default=0, max_length=10)),
            ],
        ),
    ]
