# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_recieptdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieptdetails',
            name='ass_fees',
            field=models.FloatField(blank=True, default=0, max_length=10),
        ),
    ]
