# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20171222_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsout',
            name='bank_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bankAccountDetails'),
        ),
    ]
