# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20171223_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recieptdetails',
            name='ass_bank_acc',
        ),
        migrations.AlterField(
            model_name='accountsin',
            name='bank_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bankAccountDetails'),
        ),
        migrations.AlterField(
            model_name='accountsin',
            name='reciept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.recieptDetails'),
        ),
        migrations.AlterField(
            model_name='accountsout',
            name='reciept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.recieptDetails'),
        ),
    ]
