# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_recieptdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsin',
            name='reciept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.recieptDetail'),
        ),
        migrations.AlterField(
            model_name='accountsout',
            name='reciept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.recieptDetail'),
        ),
        migrations.DeleteModel(
            name='recieptDetails',
        ),
    ]
