# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20171223_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsin',
            name='reciept',
            field=models.CharField(max_length=50),
        ),
    ]
