# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20171223_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieptdetail',
            name='ass_bank_acc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bankAccountDetails'),
        ),
    ]
