# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20171225_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsin',
            name='staff',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='accountsout',
            name='staff',
            field=models.CharField(max_length=50),
        ),
    ]
