# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20171225_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountdetails',
            name='bank_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
