# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20171225_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsin',
            name='amount_paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
