# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_accountsin_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsin',
            name='credit',
        ),
    ]
