# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_accountsin_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsin',
            old_name='amount_paid',
            new_name='amount_to_pay',
        ),
    ]
