# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20171226_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='recieptDetailsOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept_title', models.CharField(blank=True, max_length=50)),
                ('charge', models.FloatField()),
                ('ass_bank_acc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bankAccountDetails')),
            ],
        ),
    ]
