# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_recieptdetailsout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsout',
            name='charge',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='accountsout',
            name='reciept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.recieptDetailsOut'),
        ),
        migrations.AlterField(
            model_name='recieptdetailsout',
            name='charge',
            field=models.FloatField(default=0),
        ),
    ]
