# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 05:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models

from django.contrib.postgres.operations import HStoreExtension

"""class Migration(migrations.Migration):

    operations = [
        HStoreExtension(),
    ]
"""
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20180117_0500'),
    ]

    operations = [
	HStoreExtension(),
        migrations.CreateModel(
            name='json',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsfield', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='jsontest',
        ),
    ]
