# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 21:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20180117_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='json',
            name='field',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
