# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 22:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_json_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankTransDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.FloatField(default=0, max_length=10)),
                ('closing_balance', models.FloatField(default=0, max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bankAccountDetails')),
            ],
        ),
    ]
