# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_banktransdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bankTransDetails',
            new_name='bankBalanceDetails',
        ),
    ]
