# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20180420_1448'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankbalancedetails',
            unique_together=set([('bank', 'date')]),
        ),
    ]
