# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20180420_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankRechargeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bankAccountDetails')),
            ],
        ),
    ]
