# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_bankrechargedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountdetails',
            name='current_balance',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
