# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_bankaccountdetails_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbalancedetails',
            name='margin_amount',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
