# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_bankbalancedetails_margin_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankbalancedetails',
            name='margin_amount',
        ),
        migrations.AddField(
            model_name='bankaccountdetails',
            name='margin_amount',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
