# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanagement', '0002_auto_20170930_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='profile_photo',
            field=models.FileField(default='', upload_to=b''),
        ),
    ]
