# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanagement', '0003_staffdetails_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='profile_photo',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
