# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanagement', '0006_auto_20171223_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
