# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanagement', '0007_auto_20171223_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
