# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanagement', '0008_auto_20180117_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdetails',
            name='profile_photo',
        ),
    ]
