# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanagement', '0012_auto_20180421_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
